[package]
name = "recrust"
edition = "2021"
# Convention: major/minor is equal to rec's major/minor
# Note that this line will be automatically updated to the value
# BUILDER_VERSION when a release tarball is built
# See builder-support/helpers/update-rust-library-version.py
# called from meson-dist-script.sh
version = "5.4.0"

[lib]
name = "recrust"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.181" # issue #16101
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.9.34" }
ipnet = "2.8"
once_cell = "1.18.0"
base64 = "0.22"
hyper = { version = "1", features = ["server", "http1"]}
tokio = { version = "1" , features = ["rt", "net"]}
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["tokio"]}
bytes = "1.8"
form_urlencoded = "1.2"
hyper-rustls = { version = "0.27",  default-features = false }
ring = "0.17.13"
rustls = { version = "0.23", default-features = false, features = ["ring"] }
rustls-pemfile = "2.2"
pki-types = { package = "rustls-pki-types", version = "1.10" }
tokio-rustls = { version = "0.26", default-features = false }

[build-dependencies]
cxx-build = "1.0"

