[package]
name = "dnsdist-rust"
edition = "2021"
description = "Rust-based static library for DNSdist"
license = "GPL-2.0-only"
# Convention: major/minor is equal to DNSdist's major/minor
# Note that this line will be automatically updated to the value
# BUILDER_VERSION when a release tarball is built
# See builder-support/helpers/update-rust-library-version.py
# called from meson-dist-script.sh
version = "2.0.0"

[lib]
name = "dnsdist_rust"
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = { version = "0.9.34" }

[build-dependencies]
cxx-build = "1.0"
