---
name: 'daily: build packages for master '

on:
  schedule:
    - cron: '0 5 * * *'

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  call-build-packages-auth:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'authoritative'
      ref: master
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}

  call-build-packages-dnsdist:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'dnsdist'
      ref: master
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}

  call-build-packages-rec:
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'recursor'
      ref: master
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
