---
name: Trigger workflow build-and-test-all for different releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 4'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  actions: read
  contents: read

jobs:
  call-build-and-test-all-master-debian-11:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@master
    with:
      branch-name: master
      runner-docker-image-name: base-pdns-ci-image/debian-11-pdns-base

  call-build-and-test-all-auth-50:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@rel/auth-5.0.x
    with:
      branch-name: rel/auth-5.0.x

  call-build-and-test-all-auth-49:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@rel/auth-4.9.x
    with:
      branch-name: rel/auth-4.9.x

  call-build-and-test-all-auth-48:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@rel/auth-4.8.x
    with:
      branch-name: rel/auth-4.8.x

  call-build-and-test-all-rec-52:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@rel/rec-5.2.x
    with:
      branch-name: rel/rec-5.2.x

  call-build-and-test-all-rec-51:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@rel/rec-5.1.x
    with:
      branch-name: rel/rec-5.1.x

  call-build-and-test-all-rec-50:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@rel/rec-5.0.x
    with:
      branch-name: rel/rec-5.0.x

  call-build-and-test-all-dnsdist-19:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@rel/dnsdist-1.9.x
    with:
      branch-name: rel/dnsdist-1.9.x

  call-build-and-test-all-dnsdist-18:
    if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: PowerDNS/pdns/.github/workflows/build-and-test-all.yml@rel/dnsdist-1.8.x
    with:
      branch-name: rel/dnsdist-1.8.x
