---
name: 'Test package building for specific distributions'

on:
  workflow_call:
    inputs:
      branch-name:
        description: 'Checkout to a specific branch'
        required: true
        default: ''
        type: string
  schedule:
    - cron: '0 1 * * *'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

jobs:
  build:
    name: build.sh
    # on a ubuntu-22.04 VM
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        product: ['authoritative']
        os:
          - el-7
          - ubuntu-bionic
          - el-8
          - centos-9-stream
          - ubuntu-jammy
          - debian-bookworm
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for correct version numbers
          submodules: recursive
          ref: ${{ inputs.branch-name }}
      # this builds packages and runs our unit test (make check)
      - run: builder/build.sh -v -m ${{ matrix.product }} ${{ matrix.os }}
      - name: Get version number
        run: |
          echo "version=$(readlink builder/tmp/latest)" >> $GITHUB_OUTPUT
        id: getversion
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.product }}-${{ matrix.os }}-${{ steps.getversion.outputs.version }}
          path: built_pkgs/
          retention-days: 7
