---
name: Trigger build of packages on exotic distributions for a specific ref

on:
  workflow_dispatch:
    inputs:
      ref:
        description: git ref to checkout
        type: string
        default: master

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

jobs:
  build:
    name: call the workflow to build packages
    uses: PowerDNS/pdns/.github/workflows/builder.yml@master
    with:
      branch-name: ${{ github.event.inputs.ref }}
