---
name: Trigger workflow build-packages for different releases

on:
  schedule:
    - cron: '0 3 * * *'

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  call-build-packages-auth-50:
    if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'authoritative'
      ref: rel/auth-5.0.x
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-auth-49:
    if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'authoritative'
      ref: rel/auth-4.9.x
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-auth-48:
    if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'authoritative'
      ref: rel/auth-4.8.x
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-rec-53:
    if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'recursor'
      ref: rel/rec-5.3.x
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-rec-52:
    if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'recursor'
      ref: rel/rec-5.2.x
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-rec-51:
    if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'recursor'
      ref: rel/rec-5.1.x
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-dnsdist-20:
    if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'dnsdist'
      ref: rel/dnsdist-2.0.x
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-dnsdist-19:
    if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: PowerDNS/pdns/.github/workflows/build-packages.yml@master
    with:
      is_release: 'NO'
      product: 'dnsdist'
      ref: rel/dnsdist-1.9.x
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}
