---
name: 'Verify formatting and Makefile.am sort order'

on:
  push:
  pull_request:

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

jobs:
  build:
    name: verify formatting and Makefile.am sort order
    # on a ubuntu-22.04 VM
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: recursive
      - name: Update dependencies
        run: |
          sudo apt-get update
          sudo apt-get -qq --no-install-recommends install git clang-11
      - name: Run format-code on files that should be formatted
        run: |
           ./build-scripts/format-code $(find . -type f -name '*.[ch][ch]' | sort | comm -23 - .not-formatted)
           git --no-pager diff
           exit $(git diff | wc -l)
      - name: Report file names that are out of order in Makefile.am files
        run: |
           exitcode=0
           for f in $(find . -type f -name 'Makefile.am'); do
             ./build-scripts/test-sources-sorted.py ${f}
             if [ $? -ne 0 ]; then
               exitcode=1
             fi
           done
           exit ${exitcode}
