---
name: 'Verify secpoll zone syntax'

on:
  push:
  pull_request:

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

jobs:
  build:
    name: check secpoll zone
    # on a ubuntu-24.04 VM
    runs-on: ubuntu-24.04
    steps:
      - uses: PowerDNS/pdns/set-ubuntu-mirror@meta
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: recursive
      - run: sh docs/secpoll-check.sh docs/secpoll.zone
      - run: echo 'deb [arch=amd64] http://repo.powerdns.com/ubuntu noble-auth-master main' | sudo tee /etc/apt/sources.list.d/pdns.list
      - run: "echo -ne 'Package: pdns-*\nPin: origin repo.powerdns.com\nPin-Priority: 600\n' | sudo tee /etc/apt/preferences.d/pdns"
      - run: sudo curl https://repo.powerdns.com/CBC8B383-pub.asc -o /etc/apt/trusted.gpg.d/CBC8B383-pub.asc
      - run: sudo apt-get update
      - run: sudo systemctl mask pdns
      - run: sudo apt-get install -y pdns-server pdns-backend-sqlite3
      - run: "echo -ne 'launch=gsqlite3\ngsqlite3-database=/var/lib/powerdns/pdns.sqlite3\n' | sudo tee /etc/powerdns/pdns.conf"
      - run: sudo sqlite3 /var/lib/powerdns/pdns.sqlite3 < /usr/share/doc/pdns-backend-sqlite3/schema.sqlite3.sql
      - run: sudo pdnsutil load-zone secpoll.powerdns.com docs/secpoll.zone
      - run: sudo pdnsutil check-zone secpoll.powerdns.com
