# spelling.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
# spelling2.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-p8r9-69g4-jwqq
name: Spell checking

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "**"
    types:
      - "opened"
      - "reopened"
      - "synchronize"

jobs:
  spelling:
    name: Spell checking
    permissions:
      # contents-read is needed to checkout in private repositories
      contents: read
      # pull-requests-read is needed for suppress_push_for_open_pull_request in private repositories
      pull-requests: read
      # actions-read is needed (possibly only for private repositories)
      # to identify the workflow's filename until
      # https://github.com/actions/runner/issues/853 is fixed
      actions: read
      # security-events-write is needed according to the documentation:
      # https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#uploading-a-code-scanning-analysis-with-github-actions
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: ${{ contains(github.event_name, 'pull_request') || github.event_name == 'push' }}
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@v0.0.22
        with:
          config: .github/actions/spell-check
          suppress_push_for_open_pull_request: ${{ github.actor != 'dependabot[bot]' && 1 }}
          checkout: true
          check_file_names: 1
          spell_check_this: powerdns/pdns@master
          post_comment: 0
          use_magic_file: 1
          warnings: bad-regex,binary-file,deprecated-feature,ignored-expect-variant,large-file,limited-references,no-newline-at-eof,noisy-file,non-alpha-in-dictionary,token-is-substring,unexpected-line-ending,whitespace-in-dictionary,minified-file,unsupported-configuration,no-files-to-check,unclosed-block-ignore-begin,unclosed-block-ignore-end
          use_sarif: ${{ (!github.event.pull_request || (github.event.pull_request.head.repo.full_name == github.repository)) && 1 }}
          extra_dictionaries: |
            cspell:software-terms/dict/softwareTerms.txt
            cspell:python/src/common/extra.txt
            cspell:node/dict/node.txt
            cspell:php/dict/php.txt
            cspell:python/src/python/python-lib.txt
            cspell:python/src/python/python.txt
            cspell:fullstack/dict/fullstack.txt
            cspell:golang/dict/go.txt
            cspell:aws/aws.txt
            cspell:k8s/dict/k8s.txt
            cspell:cpp/src/stdlib-cpp.txt
            cspell:filetypes/filetypes.txt
            cspell:typescript/dict/typescript.txt
            cspell:html/dict/html.txt
            cspell:django/dict/django.txt
            cspell:java/src/java.txt
            cspell:dotnet/dict/dotnet.txt
            cspell:r/src/r.txt
            cspell:npm/dict/npm.txt
            cspell:lisp/lisp.txt
            cspell:cpp/src/lang-jargon.txt
            cspell:rust/dict/rust.txt
            cspell:cpp/src/lang-keywords.txt
            cspell:latex/dict/latex.txt
            cspell:cpp/src/stdlib-c.txt
            cspell:cpp/src/ecosystem.txt
            cspell:lua/dict/lua.txt
            cspell:java/src/java-terms.txt
          check_extra_dictionaries: ''
