# spelling.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p
# spelling2.yml is blocked per https://github.com/check-spelling/check-spelling/security/advisories/GHSA-p8r9-69g4-jwqq
name: Spell checking

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
    branches:
      - "**"
    tags-ignore:
      - "**"
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

jobs:
  spelling:
    name: Spell checking
    permissions:
      contents: read
      actions: read
      security-events: write
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
    - name: check-spelling
      id: spelling
      uses: check-spelling/check-spelling@v0.0.21
      with:
        config: .github/actions/spell-check
        checkout: true
        spell_check_this: check-spelling/spell-check-this@prerelease
        post_comment: 0
        use_sarif: ${{ (!github.event.pull_request || (github.event.pull_request.head.repo.full_name == github.repository)) && 1 }}
        extra_dictionaries:
          cspell:software-terms/src/software-terms.txt
          cspell:python/src/python/python-lib.txt
          cspell:node/node.txt
          cspell:python/src/common/extra.txt
          cspell:fullstack/fullstack.txt
          cspell:html/html.txt
          cspell:aws/aws.txt
          cspell:npm/npm.txt
          cspell:cpp/src/stdlib-cpp.txt
          cspell:python/src/python/python.txt
          cspell:django/django.txt
        check_extra_dictionaries: ''
